name: tyche
channels:
  - conda-forge
  - defaults
dependencies:
  - aiofiles
  - appdirs
  - argon2-cffi
  - async_generator
  - attrs
  - backcall
  - backports
  - backports.functools_lru_cache
  - bleach
  - blinker
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - click
  - cycler
  - decorator
  - defusedxml
  - entrypoints
  - expat
  - freetype
  - gettext
  - glib
  - h11
  - h2
  - hpack
  - hypercorn
  - hyperframe
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - itsdangerous
  - jedi
  - jinja2
  - joblib
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyterlab_pygments
  - kiwisolver
  - lcms2
  - libblas
  - libcblas
  - libffi
  - libiconv
  - liblapack
  - libopenblas
  - libpng
  - libsodium
  - libtiff
  - libwebp-base
  - llvm-openmp
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mistune
  - nbclient
  - nbconvert
  - nbformat
  - nest-asyncio
  - nose
  - notebook
  - numpy
  - olefile
  - openssl
  - outcome
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - patsy
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - ply
  - priority
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - ptyprocess
  - pycparser
  - pygments
  - pyomo
  - pyparsing
  - pyqt
  - pyrsistent
  - python
  - python-dateutil
  - python_abi
  - pytz
  - pyutilib
  - pyzmq
  - qt
  - qtconsole
  - qtpy
  - quart
  - scikit-learn
  - scipy
  - seaborn
  - seaborn-base
  - send2trash
  - setuptools
  - sip
  - six
  - sniffio
  - sortedcontainers
  - sqlite
  - statsmodels
  - terminado
  - testpath
  - threadpoolctl
  - tk
  - toml
  - tornado
  - traitlets
  - trio
  - typing_extensions
  - wcwidth
  - webencodings
  - werkzeug
  - wheel
  - widgetsnbextension
  - wsproto
  - xz
  - zeromq
  - zipp
  - zlib
  - zstd

